services:
  server:
    image: rifkinauvaldzaki/company-profile:latest
    container_name: company-profile-container  
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_EMAILJS_SERVICE_ID
      NEXT_PUBLIC_EMAILJS_TEMPLATE_ID
      NEXT_PUBLIC_EMAILJS_USER_ID
    command: npm start -- -p 3003
    expose:
      - 3003  # Expose port 3002 within the Docker network
    
  

